import React from "react";

function Terms() {
  return (
    <div>
      <h1>Terms & Conditions</h1>
      <p>
        Welcome to Bun Drop! These Terms and Conditions govern your use of our
        website and the services we provide. By accessing and using our website
        and placing orders with Bun Drop, you agree to comply with these terms.
        Please read them carefully. Ordering and Delivery You must be at least
        18 years old to place an order with Bun Drop. Orders can be placed
        through our website or designated mobile application. Delivery is
        available within our specified service areas, subject to availability.
        Delivery times may vary based on weather conditions, airspace
        regulations, and other factors outside our control. Delivery fees may
        apply and will be clearly stated during the checkout process. Orders are
        typically delivered by drones to the specified delivery address. Please
        ensure that the delivery location is accessible and safe for drone
        landing. In the event of unforeseen circumstances or technical issues,
        we may utilize alternative delivery methods. Menu and Pricing Our menu
        offerings and prices are subject to change without prior notice. We
        strive to provide accurate descriptions and images of our products, but
        slight variations may occur. All prices are listed in the local currency
        and are inclusive of applicable taxes. Payment Payments can be made
        securely through our website or designated mobile application. Accepted
        payment methods include major credit cards, debit cards, and other
        electronic payment options. Orders will only be processed upon
        successful payment authorization. Refunds and Returns We take utmost
        care in preparing and delivering your orders. However, if you encounter
        any issues with your order, please contact our customer support team
        within 24 hours of delivery. Refunds or replacements may be offered at
        our discretion for valid claims of order errors, quality issues, or
        damaged items. (text generated by ChatGPT 2023-05-31)
      </p>
    </div>
  );
}

export default Terms;
